/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PostRouteImport } from './routes/post'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as MePostsRouteImport } from './routes/me.posts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MePostsRoute = MePostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => MeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
  '/me/posts': typeof MePostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
  '/me/posts': typeof MePostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
  '/me/posts': typeof MePostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compose'
    | '/login'
    | '/me'
    | '/notifications'
    | '/post'
    | '/search'
    | '/tasks'
    | '/me/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compose'
    | '/login'
    | '/me'
    | '/notifications'
    | '/post'
    | '/search'
    | '/tasks'
    | '/me/posts'
  id:
    | '__root__'
    | '/'
    | '/compose'
    | '/login'
    | '/me'
    | '/notifications'
    | '/post'
    | '/search'
    | '/tasks'
    | '/me/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposeRoute: typeof ComposeRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PostRoute: typeof PostRoute
  SearchRoute: typeof SearchRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/posts': {
      id: '/me/posts'
      path: '/posts'
      fullPath: '/me/posts'
      preLoaderRoute: typeof MePostsRouteImport
      parentRoute: typeof MeRoute
    }
  }
}

interface MeRouteChildren {
  MePostsRoute: typeof MePostsRoute
}

const MeRouteChildren: MeRouteChildren = {
  MePostsRoute: MePostsRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposeRoute: ComposeRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PostRoute: PostRoute,
  SearchRoute: SearchRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
